{{- if .Values.server.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "boring-registry.fullname" . }}
  namespace: {{ include "boring-registry.namespace" . }}
  labels:
    {{- include "boring-registry.labels" . | nindent 4 }}
  {{- with .Values.server.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.cachingProxy.enabled | ternary "nginx" "api" }}
      protocol: TCP
      name: http
  selector:
    {{- include "boring-registry.selectorLabels" . | nindent 4 }}
{{- end }}
